name: Go
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

env:
  GO111MODULE: on

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with: { go-version: '1.24.x' }

      - name: Check out code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Cache go mod
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: golangci-lint
        with: { version: latest }
        uses: golangci/golangci-lint-action@v8

      - name: dump dependencies (for nancy)
        run: go list -json -m all > go.list

      - name: Nancy (deps vulnerabilities)
        uses: sonatype-nexus-community/nancy-github-action@main

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    strategy: { matrix: { go: [ '1.24.x' ] } }
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Cache go mod
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.go == '1.24.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          files: ./coverage.txt
          fail_ci_if_error: true #optional (default = false)

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}
